# Generated by Django 4.0.4 on 2022-04-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DhakaSubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('bn_name', models.CharField(max_length=150)),
                ('lat', models.FloatField(max_length=128)),
                ('lng', models.FloatField(max_length=128)),
            ],
        ),
    ]
