# Generated by Django 4.0.4 on 2022-04-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhakasubarea',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
